deployment:
  tasks:
    - export NODE_ENV=development
    - /bin/echo "Starting deployment..."
    - npm install --production
    - /bin/echo "Restarting app..."
    - /usr/local/bin/refresh-app Qsys-v4

env:
  NODE_ENV: development
