# .cpanel.yml
# Automatic deployment config for cPanel Git Version Control
deployment:
  tasks:
    - export NODE_ENV=production
    - npm install --production
    - echo "Starting deployment..."
    - /usr/local/bin/refresh-app Qsys-v4
